In [1]:
import math

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.formula.api as smf
from statsmodels.sandbox.regression.predstd import wls_prediction_std

%matplotlib inline
sns.set_style('white')

In [3]:
data_raw = pd.read_csv(open('NewYork2014.csv','rU'), encoding='utf-8', engine='c')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 'U' mode is deprecated
  """Entry point for launching an IPython kernel.

In [4]:
data_raw

,City,Population,ViolentCrime,Murder,Rape (revised definition)1,Rape2,Robbery,AggravatedAssault,PropertyCrime,Burglary,LarcenyTheft,VehicleTheft,Arson3,Unnamed: 13
0,Adams Village,"1,851",0,0.0,NaN,0.0,0,0,11,1,10,0,0.0,NaN
1,Addison Town and Village,"2,568",2,0.0,NaN,0.0,1,1,49,1,47,1,0.0,NaN
2,Afton Village4,820,0,0.0,0,NaN,0,0,1,0,1,0,0.0,NaN
3,Akron Village,"2,842",1,0.0,NaN,0.0,0,1,17,0,17,0,0.0,NaN
4,Albany4,"98,595",802,8.0,54,NaN,237,503,"3,888",683,"3,083",122,12.0,NaN
5,Albion Village4,"5,872",26,0.0,3,NaN,2,21,204,41,159,4,0.0,NaN
6,Alexandria Bay Village4,"1,107",0,0.0,0,NaN,0,0,7,2,5,0,0.0,NaN
7,Alfred Village4,"4,032",11,1.0,1,NaN,0,9,30,6,24,0,0.0,NaN
8,Altamont Village4,"1,723",1,0.0,0,NaN,0,1,2,2,0,0,0.0,NaN
9,Amherst Town4,"118,860",128,1.0,16,NaN,43,68,"2,066",176,"1,846",44,2.0,NaN
10,Amity Town and Belmont Village4,"2,250",0,0.0,0,NaN,0,0,0,0,0,0,0.0,NaN
11,Amityville Village,"9,509",12,0.0,NaN,0.0,11,1,198,10,175,13,1.0,NaN
12,Amsterdam,"18,099",27,0.0,NaN,0.0,15,12,490,107,370,13,3.0,NaN
13,Angelica Village4,846,1,0.0,0,NaN,0,1,6,4,2,0,0.0,NaN
14,Arcade Village,"2,030",0,0.0,NaN,0.0,0,0,25,7,18,0,0.0,NaN
15,Ardsley Village,"4,561",1,0.0,NaN,0.0,0,1,25,6,19,0,NaN,NaN
16,Asharoken Village,656,0,0.0,NaN,0.0,0,0,6,0,4,2,0.0,NaN
17,Attica Village,"2,502",0,0.0,NaN,0.0,0,0,12,0,12,0,2.0,NaN
18,Avon Village4,"3,333",2,0.0,0,NaN,1,1,14,1,11,2,0.0,NaN
19,Baldwinsville Village4,"7,485",2,0.0,1,NaN,0,1,65,1,60,4,0.0,NaN
20,Ballston Spa Village4,"5,470",8,0.0,0,NaN,2,6,73,21,51,1,0.0,NaN
21,Batavia4,"15,223",71,0.0,17,NaN,12,42,599,115,476,8,3.0,NaN
22,Bath Village4,"5,703",14,0.0,3,NaN,3,8,148,21,126,1,1.0,NaN
23,Beacon4,"14,330",43,0.0,3,NaN,17,23,245,38,201,6,0.0,NaN
24,Bedford Town4,"17,782",2,0.0,1,NaN,0,1,123,12,109,2,1.0,NaN
25,Bethlehem Town4,"34,653",34,0.0,7,NaN,6,21,454,58,385,11,3.0,NaN
26,Binghamton4,"46,229",305,1.0,49,NaN,82,173,"2,048",343,"1,653",52,5.0,NaN
27,Black River,"1,392",0,0.0,NaN,0.0,0,0,3,1,2,0,0.0,NaN
28,Blooming Grove Town4,"11,960",8,0.0,0,NaN,2,6,86,18,59,9,0.0,NaN
29,Bolton Town,"2,321",0,0.0,NaN,0.0,0,0,9,3,6,0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,Waterford Town and Village,"8,398",1,0.0,NaN,0.0,1,0,58,14,44,0,0.0,NaN
347,Waterloo Village4,"5,185",13,0.0,2,NaN,1,10,154,22,127,5,0.0,NaN
348,Watertown4,"28,009",153,0.0,47,NaN,17,89,"1,296",193,"1,097",6,3.0,NaN
349,Watervliet4,"10,235",20,0.0,2,NaN,10,8,199,32,152,15,0.0,NaN
350,Watkins Glen Village4,"1,871",2,0.0,0,NaN,0,2,103,10,93,0,0.0,NaN
351,Waverly Village4,"4,344",4,0.0,2,NaN,0,2,20,6,13,1,0.0,NaN
352,Webster Town and Village4,"44,230",27,1.0,6,NaN,7,13,496,67,418,11,1.0,NaN
353,Weedsport Village,"1,796",2,0.0,NaN,0.0,0,2,21,7,14,0,0.0,NaN
354,Wellsville Village,"4,576",18,0.0,NaN,0.0,0,18,156,40,114,2,1.0,NaN
355,Westfield Village4,"3,147",1,0.0,0,NaN,0,1,9,2,7,0,2.0,NaN
356,Westhampton Beach Village,"1,753",2,0.0,NaN,0.0,0,2,33,8,23,2,0.0,NaN
357,West Seneca Town4,"44,866",38,0.0,3,NaN,17,18,764,111,631,22,1.0,NaN
358,Whitehall Village4,"2,598",13,0.0,3,NaN,0,10,44,6,37,1,0.0,NaN
359,White Plains4,"58,103",105,1.0,5,NaN,25,74,"1,046",55,968,23,0.0,NaN
360,Whitesboro Village,"3,727",5,0.0,NaN,0.0,1,4,41,10,29,2,0.0,NaN
361,Whitestown Town,"9,307",0,0.0,NaN,0.0,0,0,71,16,55,0,0.0,NaN
362,Windham Town4,"1,682",1,0.0,0,NaN,0,1,18,8,9,1,0.0,NaN
363,Wolcott Village,"1,646",0,0.0,NaN,0.0,0,0,4,0,4,0,0.0,NaN
364,"Woodbury Town4, 5","10,739",4,0.0,0,NaN,1,3,NaN,5,NaN,0,0.0,NaN
365,Woodstock Town4,"5,907",3,0.0,1,NaN,2,0,43,14,29,0,0.0,NaN
366,Yonkers4,"200,624",974,3.0,33,NaN,358,580,"2,009",414,"1,395",200,15.0,NaN
367,Yorktown Town4,"36,989",13,0.0,0,NaN,0,13,209,24,182,3,0.0,NaN
368,Youngstown Village4,"1,896",0,0.0,0,NaN,0,0,1,0,1,0,0.0,NaN
369,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
370,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
371,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
372,4 This agency began the year submitting rape d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373,5 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data_raw['pop_num'] = pd.to_numeric(data_raw['Population'].str.replace(',',''))
data_raw['pop_squared']=data_raw['pop_num']**2
data_raw['Murder_Cat'] = np.where((data_raw['Murder'] > 0),1,0)
data_raw['robbery_num'] = pd.to_numeric(data_raw['Robbery'].str.replace(',',''))
data_raw['robbery_cat'] = np.where((data_raw['robbery_num'] > 0),1,0)
data_raw['Burglary'] = pd.to_numeric(data_raw['Burglary'].str.replace(',',''))
data_raw['ViolentCrime'] = pd.to_numeric(data_raw['ViolentCrime'].str.replace(',',''))
data_raw['LarcenyTheft'] = pd.to_numeric(data_raw['LarcenyTheft'].str.replace(',',''))
data_raw['VehicleTheft'] = pd.to_numeric(data_raw['VehicleTheft'].str.replace(',',''))

In [8]:
data_raw['AggravatedAssault'] = pd.to_numeric(data_raw['AggravatedAssault'].str.replace(',',''))
data_raw['PropertyCrime'] = pd.to_numeric(data_raw['PropertyCrime'].str.replace(',',''))

In [9]:
data_raw.dtypes

City                             object
Population                       object
ViolentCrime                    float64
Murder                          float64
Rape\n(revised\ndefinition)1     object
Rape2                           float64
Robbery                          object
AggravatedAssault               float64
PropertyCrime                   float64
Burglary                        float64
LarcenyTheft                    float64
VehicleTheft                    float64
Arson3                          float64
Unnamed: 13                     float64
pop_num                         float64
pop_squared                     float64
Murder_Cat                        int64
robbery_num                     float64
robbery_cat                       int64
dtype: object

In [10]:
data_raw

,City,Population,ViolentCrime,Murder,Rape (revised definition)1,Rape2,Robbery,AggravatedAssault,PropertyCrime,Burglary,LarcenyTheft,VehicleTheft,Arson3,Unnamed: 13,pop_num,pop_squared,Murder_Cat,robbery_num,robbery_cat
0,Adams Village,"1,851",0.0,0.0,NaN,0.0,0,0.0,11.0,1.0,10.0,0.0,0.0,NaN,1851.0,3.426201e+06,0,0.0,0
1,Addison Town and Village,"2,568",2.0,0.0,NaN,0.0,1,1.0,49.0,1.0,47.0,1.0,0.0,NaN,2568.0,6.594624e+06,0,1.0,1
2,Afton Village4,820,0.0,0.0,0,NaN,0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,820.0,6.724000e+05,0,0.0,0
3,Akron Village,"2,842",1.0,0.0,NaN,0.0,0,1.0,17.0,0.0,17.0,0.0,0.0,NaN,2842.0,8.076964e+06,0,0.0,0
4,Albany4,"98,595",802.0,8.0,54,NaN,237,503.0,3888.0,683.0,3083.0,122.0,12.0,NaN,98595.0,9.720974e+09,1,237.0,1
5,Albion Village4,"5,872",26.0,0.0,3,NaN,2,21.0,204.0,41.0,159.0,4.0,0.0,NaN,5872.0,3.448038e+07,0,2.0,1
6,Alexandria Bay Village4,"1,107",0.0,0.0,0,NaN,0,0.0,7.0,2.0,5.0,0.0,0.0,NaN,1107.0,1.225449e+06,0,0.0,0
7,Alfred Village4,"4,032",11.0,1.0,1,NaN,0,9.0,30.0,6.0,24.0,0.0,0.0,NaN,4032.0,1.625702e+07,1,0.0,0
8,Altamont Village4,"1,723",1.0,0.0,0,NaN,0,1.0,2.0,2.0,0.0,0.0,0.0,NaN,1723.0,2.968729e+06,0,0.0,0
9,Amherst Town4,"118,860",128.0,1.0,16,NaN,43,68.0,2066.0,176.0,1846.0,44.0,2.0,NaN,118860.0,1.412770e+10,1,43.0,1
10,Amity Town and Belmont Village4,"2,250",0.0,0.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2250.0,5.062500e+06,0,0.0,0
11,Amityville Village,"9,509",12.0,0.0,NaN,0.0,11,1.0,198.0,10.0,175.0,13.0,1.0,NaN,9509.0,9.042108e+07,0,11.0,1
12,Amsterdam,"18,099",27.0,0.0,NaN,0.0,15,12.0,490.0,107.0,370.0,13.0,3.0,NaN,18099.0,3.275738e+08,0,15.0,1
13,Angelica Village4,846,1.0,0.0,0,NaN,0,1.0,6.0,4.0,2.0,0.0,0.0,NaN,846.0,7.157160e+05,0,0.0,0
14,Arcade Village,"2,030",0.0,0.0,NaN,0.0,0,0.0,25.0,7.0,18.0,0.0,0.0,NaN,2030.0,4.120900e+06,0,0.0,0
15,Ardsley Village,"4,561",1.0,0.0,NaN,0.0,0,1.0,25.0,6.0,19.0,0.0,NaN,NaN,4561.0,2.080272e+07,0,0.0,0
16,Asharoken Village,656,0.0,0.0,NaN,0.0,0,0.0,6.0,0.0,4.0,2.0,0.0,NaN,656.0,4.303360e+05,0,0.0,0
17,Attica Village,"2,502",0.0,0.0,NaN,0.0,0,0.0,12.0,0.0,12.0,0.0,2.0,NaN,2502.0,6.260004e+06,0,0.0,0
18,Avon Village4,"3,333",2.0,0.0,0,NaN,1,1.0,14.0,1.0,11.0,2.0,0.0,NaN,3333.0,1.110889e+07,0,1.0,1
19,Baldwinsville Village4,"7,485",2.0,0.0,1,NaN,0,1.0,65.0,1.0,60.0,4.0,0.0,NaN,7485.0,5.602522e+07,0,0.0,0
20,Ballston Spa Village4,"5,470",8.0,0.0,0,NaN,2,6.0,73.0,21.0,51.0,1.0,0.0,NaN,5470.0,2.992090e+07,0,2.0,1
21,Batavia4,"15,223",71.0,0.0,17,NaN,12,42.0,599.0,115.0,476.0,8.0,3.0,NaN,15223.0,2.317397e+08,0,12.0,1
22,Bath Village4,"5,703",14.0,0.0,3,NaN,3,8.0,148.0,21.0,126.0,1.0,1.0,NaN,5703.0,3.252421e+07,0,3.0,1
23,Beacon4,"14,330",43.0,0.0,3,NaN,17,23.0,245.0,38.0,201.0,6.0,0.0,NaN,14330.0,2.053489e+08,0,17.0,1
24,Bedford Town4,"17,782",2.0,0.0,1,NaN,0,1.0,123.0,12.0,109.0,2.0,1.0,NaN,17782.0,3.161995e+08,0,0.0,0
25,Bethlehem Town4,"34,653",34.0,0.0,7,NaN,6,21.0,454.0,58.0,385.0,11.0,3.0,NaN,34653.0,1.200830e+09,0,6.0,1
26,Binghamton4,"46,229",305.0,1.0,49,NaN,82,173.0,2048.0,343.0,1653.0,52.0,5.0,NaN,46229.0,2.137120e+09,1,82.0,1
27,Black River,"1,392",0.0,0.0,NaN,0.0,0,0.0,3.0,1.0,2.0,0.0,0.0,NaN,1392.0,1.937664e+06,0,0.0,0
28,Blooming Grove Town4,"11,960",8.0,0.0,0,NaN,2,6.0,86.0,18.0,59.0,9.0,0.0,NaN,11960.0,1.430416e+08,0,2.0,1
29,Bolton Town,"2,321",0.0,0.0,NaN,0.0,0,0.0,9.0,3.0,6.0,0.0,0.0,NaN,2321.0,5.387041e+06,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,Waterford Town and Village,"8,398",1.0,0.0,NaN,0.0,1,0.0,58.0,14.0,44.0,0.0,0.0,NaN,8398.0,7.052640e+07,0,1.0,1
347,Waterloo Village4,"5,185",13.0,0.0,2,NaN,1,10.0,154.0,22.0,127.0,5.0,0.0,NaN,5185.0,2.688422e+07,0,1.0,1
348,Watertown4,"28,009",153.0,0.0,47,NaN,17,89.0,1296.0,193.0,1097.0,6.0,3.0,NaN,28009.0,7.845041e+08,0,17.0,1
349,Watervliet4,"10,235",20.0,0.0,2,NaN,10,8.0,199.0,32.0,152.0,15.0,0.0,NaN,10235.0,1.047552e+08,0,10.0,1
350,Watkins Glen Village4,"1,871",2.0,0.0,0,NaN,0,2.0,103.0,10.0,93.0,0.0,0.0,NaN,1871.0,3.500641e+06,0,0.0,0
351,Waverly Village4,"4,344",4.0,0.0,2,NaN,0,2.0,20.0,6.0,13.0,1.0,0.0,NaN,4344.0,1.887034e+07,0,0.0,0
352,Webster Town and Village4,"44,230",27.0,1.0,6,NaN,7,13.0,496.0,67.0,418.0,11.0,1.0,NaN,44230.0,1.956293e+09,1,7.0,1
353,Weedsport Village,"1,796",2.0,0.0,NaN,0.0,0,2.0,21.0,7.0,14.0,0.0,0.0,NaN,1796.0,3.225616e+06,0,0.0,0
354,Wellsville Village,"4,576",18.0,0.0,NaN,0.0,0,18.0,156.0,40.0,114.0,2.0,1.0,NaN,4576.0,2.093978e+07,0,0.0,0
355,Westfield Village4,"3,147",1.0,0.0,0,NaN,0,1.0,9.0,2.0,7.0,0.0,2.0,NaN,3147.0,9.903609e+06,0,0.0,0
356,Westhampton Beach Village,"1,753",2.0,0.0,NaN,0.0,0,2.0,33.0,8.0,23.0,2.0,0.0,NaN,1753.0,3.073009e+06,0,0.0,0
357,West Seneca Town4,"44,866",38.0,0.0,3,NaN,17,18.0,764.0,111.0,631.0,22.0,1.0,NaN,44866.0,2.012958e+09,0,17.0,1
358,Whitehall Village4,"2,598",13.0,0.0,3,NaN,0,10.0,44.0,6.0,37.0,1.0,0.0,NaN,2598.0,6.749604e+06,0,0.0,0
359,White Plains4,"58,103",105.0,1.0,5,NaN,25,74.0,1046.0,55.0,968.0,23.0,0.0,NaN,58103.0,3.375959e+09,1,25.0,1
360,Whitesboro Village,"3,727",5.0,0.0,NaN,0.0,1,4.0,41.0,10.0,29.0,2.0,0.0,NaN,3727.0,1.389053e+07,0,1.0,1
361,Whitestown Town,"9,307",0.0,0.0,NaN,0.0,0,0.0,71.0,16.0,55.0,0.0,0.0,NaN,9307.0,8.662025e+07,0,0.0,0
362,Windham Town4,"1,682",1.0,0.0,0,NaN,0,1.0,18.0,8.0,9.0,1.0,0.0,NaN,1682.0,2.829124e+06,0,0.0,0
363,Wolcott Village,"1,646",0.0,0.0,NaN,0.0,0,0.0,4.0,0.0,4.0,0.0,0.0,NaN,1646.0,2.709316e+06,0,0.0,0
364,"Woodbury Town4, 5","10,739",4.0,0.0,0,NaN,1,3.0,NaN,5.0,NaN,0.0,0.0,NaN,10739.0,1.153261e+08,0,1.0,1
365,Woodstock Town4,"5,907",3.0,0.0,1,NaN,2,0.0,43.0,14.0,29.0,0.0,0.0,NaN,5907.0,3.489265e+07,0,2.0,1
366,Yonkers4,"200,624",974.0,3.0,33,NaN,358,580.0,2009.0,414.0,1395.0,200.0,15.0,NaN,200624.0,4.024999e+10,1,358.0,1
367,Yorktown Town4,"36,989",13.0,0.0,0,NaN,0,13.0,209.0,24.0,182.0,3.0,0.0,NaN,36989.0,1.368186e+09,0,0.0,0
368,Youngstown Village4,"1,896",0.0,0.0,0,NaN,0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,1896.0,3.594816e+06,0,0.0,0
369,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
370,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
371,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
372,4 This agency began the year submitting rape d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
373,5 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
375,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0

In [21]:
per_capita_data = data_raw[:-7]

In [40]:
per_capita_data[:,'pc_ViolentCrime'] = per_capita_data.loc['ViolentCrime']

KeyError: 'the label [ViolentCrime] is not in the [index]'

In [ ]:
 # dfmi.loc[:,('one','second')]
per_capita_data

In [42]:
per_capita_data['pc_ViolentCrime'] = per_capita_data.loc[:,('ViolentCrime',)]

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [45]:
per_capita_data['var1'] = per_capita_data['ViolentCrime']/per_capita_data['pop_num']

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [44]:
per_capita_data

,City,Population,ViolentCrime,Murder,Rape (revised definition)1,Rape2,Robbery,AggravatedAssault,PropertyCrime,Burglary,LarcenyTheft,VehicleTheft,Arson3,Unnamed: 13,pop_num,pop_squared,Murder_Cat,robbery_num,robbery_cat,pc_ViolentCrime
0,Adams Village,"1,851",0.0,0.0,NaN,0.0,0,0.0,11.0,1.0,10.0,0.0,0.0,NaN,1851.0,3.426201e+06,0,0.0,0,0.0
1,Addison Town and Village,"2,568",2.0,0.0,NaN,0.0,1,1.0,49.0,1.0,47.0,1.0,0.0,NaN,2568.0,6.594624e+06,0,1.0,1,2.0
2,Afton Village4,820,0.0,0.0,0,NaN,0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,820.0,6.724000e+05,0,0.0,0,0.0
3,Akron Village,"2,842",1.0,0.0,NaN,0.0,0,1.0,17.0,0.0,17.0,0.0,0.0,NaN,2842.0,8.076964e+06,0,0.0,0,1.0
4,Albany4,"98,595",802.0,8.0,54,NaN,237,503.0,3888.0,683.0,3083.0,122.0,12.0,NaN,98595.0,9.720974e+09,1,237.0,1,802.0
5,Albion Village4,"5,872",26.0,0.0,3,NaN,2,21.0,204.0,41.0,159.0,4.0,0.0,NaN,5872.0,3.448038e+07,0,2.0,1,26.0
6,Alexandria Bay Village4,"1,107",0.0,0.0,0,NaN,0,0.0,7.0,2.0,5.0,0.0,0.0,NaN,1107.0,1.225449e+06,0,0.0,0,0.0
7,Alfred Village4,"4,032",11.0,1.0,1,NaN,0,9.0,30.0,6.0,24.0,0.0,0.0,NaN,4032.0,1.625702e+07,1,0.0,0,11.0
8,Altamont Village4,"1,723",1.0,0.0,0,NaN,0,1.0,2.0,2.0,0.0,0.0,0.0,NaN,1723.0,2.968729e+06,0,0.0,0,1.0
9,Amherst Town4,"118,860",128.0,1.0,16,NaN,43,68.0,2066.0,176.0,1846.0,44.0,2.0,NaN,118860.0,1.412770e+10,1,43.0,1,128.0
10,Amity Town and Belmont Village4,"2,250",0.0,0.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2250.0,5.062500e+06,0,0.0,0,0.0
11,Amityville Village,"9,509",12.0,0.0,NaN,0.0,11,1.0,198.0,10.0,175.0,13.0,1.0,NaN,9509.0,9.042108e+07,0,11.0,1,12.0
12,Amsterdam,"18,099",27.0,0.0,NaN,0.0,15,12.0,490.0,107.0,370.0,13.0,3.0,NaN,18099.0,3.275738e+08,0,15.0,1,27.0
13,Angelica Village4,846,1.0,0.0,0,NaN,0,1.0,6.0,4.0,2.0,0.0,0.0,NaN,846.0,7.157160e+05,0,0.0,0,1.0
14,Arcade Village,"2,030",0.0,0.0,NaN,0.0,0,0.0,25.0,7.0,18.0,0.0,0.0,NaN,2030.0,4.120900e+06,0,0.0,0,0.0
15,Ardsley Village,"4,561",1.0,0.0,NaN,0.0,0,1.0,25.0,6.0,19.0,0.0,NaN,NaN,4561.0,2.080272e+07,0,0.0,0,1.0
16,Asharoken Village,656,0.0,0.0,NaN,0.0,0,0.0,6.0,0.0,4.0,2.0,0.0,NaN,656.0,4.303360e+05,0,0.0,0,0.0
17,Attica Village,"2,502",0.0,0.0,NaN,0.0,0,0.0,12.0,0.0,12.0,0.0,2.0,NaN,2502.0,6.260004e+06,0,0.0,0,0.0
18,Avon Village4,"3,333",2.0,0.0,0,NaN,1,1.0,14.0,1.0,11.0,2.0,0.0,NaN,3333.0,1.110889e+07,0,1.0,1,2.0
19,Baldwinsville Village4,"7,485",2.0,0.0,1,NaN,0,1.0,65.0,1.0,60.0,4.0,0.0,NaN,7485.0,5.602522e+07,0,0.0,0,2.0
20,Ballston Spa Village4,"5,470",8.0,0.0,0,NaN,2,6.0,73.0,21.0,51.0,1.0,0.0,NaN,5470.0,2.992090e+07,0,2.0,1,8.0
21,Batavia4,"15,223",71.0,0.0,17,NaN,12,42.0,599.0,115.0,476.0,8.0,3.0,NaN,15223.0,2.317397e+08,0,12.0,1,71.0
22,Bath Village4,"5,703",14.0,0.0,3,NaN,3,8.0,148.0,21.0,126.0,1.0,1.0,NaN,5703.0,3.252421e+07,0,3.0,1,14.0
23,Beacon4,"14,330",43.0,0.0,3,NaN,17,23.0,245.0,38.0,201.0,6.0,0.0,NaN,14330.0,2.053489e+08,0,17.0,1,43.0
24,Bedford Town4,"17,782",2.0,0.0,1,NaN,0,1.0,123.0,12.0,109.0,2.0,1.0,NaN,17782.0,3.161995e+08,0,0.0,0,2.0
25,Bethlehem Town4,"34,653",34.0,0.0,7,NaN,6,21.0,454.0,58.0,385.0,11.0,3.0,NaN,34653.0,1.200830e+09,0,6.0,1,34.0
26,Binghamton4,"46,229",305.0,1.0,49,NaN,82,173.0,2048.0,343.0,1653.0,52.0,5.0,NaN,46229.0,2.137120e+09,1,82.0,1,305.0
27,Black River,"1,392",0.0,0.0,NaN,0.0,0,0.0,3.0,1.0,2.0,0.0,0.0,NaN,1392.0,1.937664e+06,0,0.0,0,0.0
28,Blooming Grove Town4,"11,960",8.0,0.0,0,NaN,2,6.0,86.0,18.0,59.0,9.0,0.0,NaN,11960.0,1.430416e+08,0,2.0,1,8.0
29,Bolton Town,"2,321",0.0,0.0,NaN,0.0,0,0.0,9.0,3.0,6.0,0.0,0.0,NaN,2321.0,5.387041e+06,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,Vernon Village,"1,166",1.0,0.0,NaN,0.0,0,1.0,15.0,2.0,13.0,0.0,0.0,NaN,1166.0,1.359556e+06,0,0.0,0,1.0
340,Vestal Town4,"28,019",11.0,0.0,4,NaN,1,6.0,580.0,38.0,524.0,18.0,0.0,NaN,28019.0,7.850644e+08,0,1.0,1,11.0
341,Walden Village4,"6,847",9.0,0.0,0,NaN,0,9.0,89.0,10.0,75.0,4.0,2.0,NaN,6847.0,4.688141e+07,0,0.0,0,9.0
342,Wallkill Town4,"28,211",43.0,0.0,2,NaN,19,22.0,506.0,59.0,430.0,17.0,2.0,NaN,28211.0,7.958605e+08,0,19.0,1,43.0
343,Walton Village4,"2,980",10.0,0.0,1,NaN,1,8.0,75.0,15.0,59.0,1.0,2.0,NaN,2980.0,8.880400e+06,0,1.0,1,10.0
344,Warsaw Village4,"3,397",5.0,0.0,1,NaN,0,4.0,75.0,6.0,69.0,0.0,1.0,NaN,3397.0,1.153961e+07,0,0.0,0,5.0
345,Washingtonville Village,"5,788",2.0,0.0,NaN,0.0,0,2.0,59.0,5.0,53.0,1.0,0.0,NaN,5788.0,3.350094e+07,0,0.0,0,2.0
346,Waterford Town and Village,"8,398",1.0,0.0,NaN,0.0,1,0.0,58.0,14.0,44.0,0.0,0.0,NaN,8398.0,7.052640e+07,0,1.0,1,1.0
347,Waterloo Village4,"5,185",13.0,0.0,2,NaN,1,10.0,154.0,22.0,127.0,5.0,0.0,NaN,5185.0,2.688422e+07,0,1.0,1,13.0
348,Watertown4,"28,009",153.0,0.0,47,NaN,17,89.0,1296.0,193.0,1097.0,6.0,3.0,NaN,28009.0,7.845041e+08,0,17.0,1,153.0
349,Watervliet4,"10,235",20.0,0.0,2,NaN,10,8.0,199.0,32.0,152.0,15.0,0.0,NaN,10235.0,1.047552e+08,0,10.0,1,20.0
350,Watkins Glen Village4,"1,871",2.0,0.0,0,NaN,0,2.0,103.0,10.0,93.0,0.0,0.0,NaN,1871.0,3.500641e+06,0,0.0,0,2.0
351,Waverly Village4,"4,344",4.0,0.0,2,NaN,0,2.0,20.0,6.0,13.0,1.0,0.0,NaN,4344.0,1.887034e+07,0,0.0,0,4.0
352,Webster Town and Village4,"44,230",27.0,1.0,6,NaN,7,13.0,496.0,67.0,418.0,11.0,1.0,NaN,44230.0,1.956293e+09,1,7.0,1,27.0
353,Weedsport Village,"1,796",2.0,0.0,NaN,0.0,0,2.0,21.0,7.0,14.0,0.0,0.0,NaN,1796.0,3.225616e+06,0,0.0,0,2.0
354,Wellsville Village,"4,576",18.0,0.0,NaN,0.0,0,18.0,156.0,40.0,114.0,2.0,1.0,NaN,4576.0,2.093978e+07,0,0.0,0,18.0
355,Westfield Village4,"3,147",1.0,0.0,0,NaN,0,1.0,9.0,2.0,7.0,0.0,2.0,NaN,3147.0,9.903609e+06,0,0.0,0,1.0
356,Westhampton Beach Village,"1,753",2.0,0.0,NaN,0.0,0,2.0,33.0,8.0,23.0,2.0,0.0,NaN,1753.0,3.073009e+06,0,0.0,0,2.0
357,West Seneca Town4,"44,866",38.0,0.0,3,NaN,17,18.0,764.0,111.0,631.0,22.0,1.0,NaN,44866.0,2.012958e+09,0,17.0,1,38.0
358,Whitehall Village4,"2,598",13.0,0.0,3,NaN,0,10.0,44.0,6.0,37.0,1.0,0.0,NaN,2598.0,6.749604e+06,0,0.0,0,13.0
359,White Plains4,"58,103",105.0,1.0,5,NaN,25,74.0,1046.0,55.0,968.0,23.0,0.0,NaN,58103.0,3.375959e+09,1,25.0,1,105.0
360,Whitesboro Village,"3,727",5.0,0.0,NaN,0.0,1,4.0,41.0,10.0,29.0,2.0,0.0,NaN,3727.0,1.389053e+07,0,1.0,1,5.0
361,Whitestown Town,"9,307",0.0,0.0,NaN,0.0,0,0.0,71.0,16.0,55.0,0.0,0.0,NaN,9307.0,8.662025e+07,0,0.0,0,0.0
362,Windham Town4,"1,682",1.0,0.0,0,NaN,0,1.0,18.0,8.0,9.0,1.0,0.0,NaN,1682.0,2.829124e+06,0,0.0,0,1.0
363,Wolcott Village,"1,646",0.0,0.0,NaN,0.0,0,0.0,4.0,0.0,4.0,0.0,0.0,NaN,1646.0,2.709316e+06,0,0.0,0,0.0
364,"Woodbury Town4, 5","10,739",4.0,0.0,0,NaN,1,3.0,NaN,5.0,NaN,0.0,0.0,NaN,10739.0,1.153261e+08,0,1.0,1,4.0
365,Woodstock Town4,"5,907",3.0,0.0,1,NaN,2,0.0,43.0,14.0,29.0,0.0,0.0,NaN,5907.0,3.489265e+07,0,2.0,1,3.0
366,Yonkers4,"200,624",974.0,3.0,33,NaN,358,580.0,2009.0,414.0,1395.0,200.0,15.0,NaN,200624.0,4.024999e+10,1,358.0,1,974.0
367,Yorktown Town4,"36,989",13.0,0.0,0,NaN,0,13.0,209.0,24.0,182.0,3.0,0.0,NaN,36989.0,1.368186e+09,0,0.0,0,13.0
368,Youngstown Village4,"1,896",0.0,0.0,0,NaN,0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,1896.0,3.594816e+06,0,0.0,0,0.0

In [46]:
per_capita_data['new_column2'].assign = var1

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [ ]:
per_capita_data.assign()